#!/bin/sh
myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to FlowForge's 1-Click Droplet.

* You can SSH to this Droplet in a terminal as root: ssh root@$myip

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})

EOF