name: Release Publish
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGTIALOCEAN_API_TOKEN }}
        run: ./build.sh